import { useAuth } from "@/_core/hooks/useAuth";
import { useLocation } from "wouter";
import { useEffect, useState } from "react";
import { Loader2, Download, FileText, Share2 } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

interface Report {
  id: string;
  name: string;
  createdAt: Date;
  type: "academic" | "transcript" | "performance";
  url: string;
}

export default function Reports() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const [reports, setReports] = useState<Report[]>([]);

  const generateAcademicMutation = trpc.reports.generateAcademic.useMutation();
  const generateTranscriptMutation = trpc.reports.generateTranscript.useMutation();
  const generatePerformanceMutation = trpc.reports.generatePerformance.useMutation();

  useEffect(() => {
    if (!loading && !user) {
      setLocation("/");
    }
  }, [loading, user, setLocation]);

  useEffect(() => {
    // Load saved reports from localStorage
    const saved = localStorage.getItem("gradeflow_reports");
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        setReports(
          parsed.map((r: any) => ({
            ...r,
            createdAt: new Date(r.createdAt),
          }))
        );
      } catch (e) {
        console.error("Failed to load reports", e);
      }
    }
  }, []);

  const handleGenerateReport = async (type: "academic" | "transcript" | "performance") => {
    try {
      let result;
      if (type === "academic") {
        result = await generateAcademicMutation.mutateAsync();
      } else if (type === "transcript") {
        result = await generateTranscriptMutation.mutateAsync();
      } else {
        result = await generatePerformanceMutation.mutateAsync();
      }

      const newReport: Report = {
        id: Date.now().toString(),
        name: `${type.charAt(0).toUpperCase() + type.slice(1)} Report - ${new Date().toLocaleDateString()}`,
        createdAt: new Date(),
        type,
        url: result.url,
      };

      setReports((prev) => [...prev, newReport]);
      localStorage.setItem(
        "gradeflow_reports",
        JSON.stringify([...reports, newReport])
      );

      toast.success(`${type} report generated successfully`);
    } catch (error) {
      toast.error(`Failed to generate ${type} report`);
      console.error(error);
    }
  };

  const handleDownloadReport = (report: Report) => {
    try {
      // Open the report URL in a new tab or download it
      window.open(report.url, "_blank");
      toast.success("Report opened");
    } catch (error) {
      toast.error("Failed to download report");
    }
  };

  const handleShareReport = (report: Report) => {
    try {
      const shareText = `Check out my academic report generated by GradeFlow!`;

      if (navigator.share) {
        navigator.share({
          title: "My Academic Report",
          text: shareText,
          url: report.url,
        });
      } else {
        // Fallback: copy to clipboard
        navigator.clipboard.writeText(report.url);
        toast.success("Report link copied to clipboard");
      }
    } catch (error) {
      toast.error("Failed to share report");
    }
  };

  const handleDeleteReport = (id: string) => {
    const updated = reports.filter((r) => r.id !== id);
    localStorage.setItem("gradeflow_reports", JSON.stringify(updated));
    setReports(updated);
    toast.success("Report deleted");
  };

  if (loading || !user) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="w-8 h-8 animate-spin text-accent" />
      </div>
    );
  }

  return (
    <DashboardLayout>
      <div className="space-y-8">
        <div>
          <h1 className="text-4xl font-bold mb-2">Academic Reports</h1>
          <p className="text-muted-foreground">
            Generate and manage your academic reports
          </p>
        </div>

        {/* Generate Report Options */}
        <Card className="p-6">
          <h2 className="text-2xl font-bold mb-6">Generate New Report</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Button
              onClick={() => handleGenerateReport("academic")}
              disabled={generateAcademicMutation.isPending}
              variant="outline"
              className="h-24 flex flex-col items-center justify-center"
            >
              {generateAcademicMutation.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin mb-2" />
              ) : (
                <FileText className="w-6 h-6 mb-2" />
              )}
              <span>Academic Report</span>
            </Button>
            <Button
              onClick={() => handleGenerateReport("transcript")}
              disabled={generateTranscriptMutation.isPending}
              variant="outline"
              className="h-24 flex flex-col items-center justify-center"
            >
              {generateTranscriptMutation.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin mb-2" />
              ) : (
                <FileText className="w-6 h-6 mb-2" />
              )}
              <span>Transcript</span>
            </Button>
            <Button
              onClick={() => handleGenerateReport("performance")}
              disabled={generatePerformanceMutation.isPending}
              variant="outline"
              className="h-24 flex flex-col items-center justify-center"
            >
              {generatePerformanceMutation.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin mb-2" />
              ) : (
                <FileText className="w-6 h-6 mb-2" />
              )}
              <span>Performance Report</span>
            </Button>
          </div>
        </Card>

        {/* Reports List */}
        <Card className="p-6">
          <h2 className="text-2xl font-bold mb-6">Your Reports</h2>
          {reports.length > 0 ? (
            <div className="space-y-4">
              {reports.map((report) => (
                <div
                  key={report.id}
                  className="flex items-center justify-between p-4 border rounded-lg hover:bg-accent/5 transition-colors"
                >
                  <div className="flex items-center gap-4">
                    <FileText className="w-6 h-6 text-accent" />
                    <div>
                      <p className="font-semibold">{report.name}</p>
                      <p className="text-sm text-muted-foreground">
                        {report.createdAt.toLocaleString()}
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => handleDownloadReport(report)}
                    >
                      <Download className="w-4 h-4" />
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => handleShareReport(report)}
                    >
                      <Share2 className="w-4 h-4" />
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => handleDeleteReport(report.id)}
                    >
                      ✕
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-12">
              <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
              <p className="text-muted-foreground mb-4">
                No reports generated yet
              </p>
              <p className="text-sm text-muted-foreground">
                Generate your first report to get started
              </p>
            </div>
          )}
        </Card>

        {/* Report Information */}
        <Card className="p-6 bg-accent/5">
          <h2 className="text-xl font-bold mb-4">Report Information</h2>
          <div className="space-y-3 text-sm">
            <p>
              <strong>Academic Report:</strong> Comprehensive overview of your
              GPA, CGPA, degree classification, and academic summary
            </p>
            <p>
              <strong>Transcript:</strong> Detailed course-by-course breakdown
              with grades, grade points, and semester organization
            </p>
            <p>
              <strong>Performance Report:</strong> Analysis of your performance
              trends, GPA progression, and personalized recommendations
            </p>
          </div>
        </Card>
      </div>
    </DashboardLayout>
  );
}
