import * as db from "./db";
import { storagePut } from "./storage";
import PDFDocument from "pdfkit";
import { Readable } from "stream";

/**
 * Generate academic performance report as PDF
 */
export async function generateAcademicReportPDF(
  userId: number,
  userName: string,
  userEmail: string
): Promise<string> {
  const gpaHistory = await db.getAllGPAHistory(userId);
  const userUni = await db.getUserUniversity(userId);

  let universityName = "Unknown University";
  if (userUni) {
    const uni = await db.getUniversityById(userUni.universityId);
    if (uni) universityName = uni.name;
  }

  // Calculate statistics
  const cgpaRaw =
    gpaHistory.length > 0
      ? typeof gpaHistory[gpaHistory.length - 1].cgpa === "number"
        ? gpaHistory[gpaHistory.length - 1].cgpa
        : parseFloat(gpaHistory[gpaHistory.length - 1].cgpa as any)
      : 0;
  const cgpa = typeof cgpaRaw === "number" ? cgpaRaw : parseFloat(cgpaRaw as any);

  let classification = "Pass";
  if (cgpa >= 3.7) classification = "First Class Honours";
  else if (cgpa >= 3.3) classification = "Second Class Upper";
  else if (cgpa >= 2.7) classification = "Second Class Lower";
  else if (cgpa >= 2.0) classification = "Third Class";

  const totalCredits = gpaHistory.reduce(
    (sum, h) => sum + h.totalCreditHours,
    0
  );

  // Create PDF document
  const doc = new PDFDocument();
  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => {
    chunks.push(chunk);
  });

  // Header
  doc.fontSize(24).font("Helvetica-Bold").text("ACADEMIC PERFORMANCE REPORT", {
    align: "center",
  });
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica").text(`Generated: ${new Date().toLocaleString()}`, {
    align: "center",
  });
  doc.moveDown(1);

  // Student Information
  doc.fontSize(14).font("Helvetica-Bold").text("STUDENT INFORMATION");
  doc.fontSize(11).font("Helvetica");
  doc.text(`Name: ${userName}`);
  doc.text(`Email: ${userEmail}`);
  doc.text(`University: ${universityName}`);
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown(1);

  // Academic Summary
  doc.fontSize(14).font("Helvetica-Bold").text("ACADEMIC SUMMARY");
  doc.fontSize(11).font("Helvetica");
  doc.text(`Current CGPA: ${cgpa.toFixed(3)}`);
  doc.text(`Degree Classification: ${classification}`);
  doc.text(`Total Semesters: ${gpaHistory.length}`);
  doc.text(`Total Credit Hours: ${totalCredits}`);
  doc.moveDown(1);

  // Semester History
  doc.fontSize(14).font("Helvetica-Bold").text("SEMESTER HISTORY");
  doc.fontSize(11).font("Helvetica");

  gpaHistory.forEach((h: any) => {
    const gpa = typeof h.gpa === "number" ? h.gpa : parseFloat(h.gpa as any);
    const cgpaVal =
      typeof h.cgpa === "number" ? h.cgpa : parseFloat(h.cgpa as any);
    doc.text(`${h.semester}:`);
    doc.text(`  GPA: ${(gpa as number).toFixed(3)}`);
    doc.text(`  CGPA: ${(cgpaVal as number).toFixed(3)}`);
    doc.text(`  Credit Hours: ${h.totalCreditHours}`);
  });

  doc.moveDown(1);

  // Classification Scale
  doc.fontSize(14).font("Helvetica-Bold").text("CLASSIFICATION SCALE");
  doc.fontSize(11).font("Helvetica");
  doc.text("First Class Honours: 3.70 - 4.00");
  doc.text("Second Class Upper: 3.30 - 3.69");
  doc.text("Second Class Lower: 2.70 - 3.29");
  doc.text("Third Class: 2.00 - 2.69");
  doc.text("Pass: 1.00 - 1.99");

  doc.moveDown(1);
  doc.fontSize(10).text("---");
  doc.fontSize(10).text(
    "This is an official academic report generated by GradeFlow."
  );

  doc.end();

  // Convert stream to buffer
  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    doc.on("finish", () => {
      resolve(Buffer.concat(chunks));
    });
    doc.on("error", reject);
  });

  // Store PDF
  const fileName = `academic-report-${userId}-${Date.now()}.pdf`;
  const { url } = await storagePut(
    `reports/${fileName}`,
    pdfBuffer,
    "application/pdf"
  );

  return url;
}

/**
 * Generate academic transcript as PDF
 */
export async function generateTranscriptPDF(
  userId: number,
  userName: string
): Promise<string> {
  const results = await db.getAllUserResults(userId);

  const doc = new PDFDocument();
  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => {
    chunks.push(chunk);
  });

  // Header
  doc.fontSize(24).font("Helvetica-Bold").text("ACADEMIC TRANSCRIPT", {
    align: "center",
  });
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica").text(`Generated: ${new Date().toLocaleString()}`, {
    align: "center",
  });
  doc.moveDown(1);

  // Student Info
  doc.fontSize(12).font("Helvetica-Bold").text("Student Information");
  doc.fontSize(11).font("Helvetica");
  doc.text(`Name: ${userName}`);
  doc.text(`Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown(1);

  // Group courses by semester
  const coursesBySection: Record<string, any[]> = {};
  for (const result of results) {
    const course = await db.getCourseById(result.courseId);
    if (!coursesBySection[result.semester]) {
      coursesBySection[result.semester] = [];
    }
    coursesBySection[result.semester].push({
      ...result,
      courseName: course?.courseName || "Unknown",
      courseCode: course?.courseCode || "N/A",
    });
  }

  // Display courses by semester
  Object.entries(coursesBySection).forEach(([semester, courses]) => {
    doc.fontSize(12).font("Helvetica-Bold").text(semester);
    doc.fontSize(10).font("Helvetica");

    (courses as any[]).forEach((c: any) => {
      const gradePoint =
        typeof c.gradePoint === "number"
          ? c.gradePoint
          : parseFloat(c.gradePoint as any);
      doc.text(
        `${c.courseCode} - ${c.courseName} | Grade: ${c.grade} | Points: ${gradePoint.toFixed(2)}`
      );
    });

    doc.moveDown(0.5);
  });

  doc.end();

  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    doc.on("finish", () => {
      resolve(Buffer.concat(chunks));
    });
    doc.on("error", reject);
  });

  const fileName = `transcript-${userId}-${Date.now()}.pdf`;
  const { url } = await storagePut(
    `reports/${fileName}`,
    pdfBuffer,
    "application/pdf"
  );

  return url;
}

/**
 * Generate performance analysis report as PDF
 */
export async function generatePerformanceReportPDF(
  userId: number,
  userName: string
): Promise<string> {
  const gpaHistory = await db.getAllGPAHistory(userId);

  const doc = new PDFDocument();
  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => {
    chunks.push(chunk);
  });

  // Header
  doc.fontSize(24).font("Helvetica-Bold").text("PERFORMANCE ANALYSIS REPORT", {
    align: "center",
  });
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica").text(`Generated: ${new Date().toLocaleString()}`, {
    align: "center",
  });
  doc.moveDown(1);

  // Student Info
  doc.fontSize(12).font("Helvetica-Bold").text("Student Information");
  doc.fontSize(11).font("Helvetica");
  doc.text(`Name: ${userName}`);
  doc.text(`Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown(1);

  // Performance Metrics
  doc.fontSize(12).font("Helvetica-Bold").text("PERFORMANCE METRICS");

  const gpas = gpaHistory.map((h: any) =>
    typeof h.gpa === "number" ? h.gpa : parseFloat(h.gpa as any)
  );
  const avgGPA =
    gpas.length > 0 ? gpas.reduce((a: number, b: number) => a + b, 0) / gpas.length : 0;
  const maxGPA = gpas.length > 0 ? Math.max(...gpas) : 0;
  const minGPA = gpas.length > 0 ? Math.min(...gpas) : 0;

  doc.fontSize(11).font("Helvetica");
  doc.text(`Average GPA: ${(avgGPA as number).toFixed(3)}`);
  doc.text(`Highest GPA: ${maxGPA.toFixed(3)}`);
  doc.text(`Lowest GPA: ${minGPA.toFixed(3)}`);
  doc.moveDown(1);

  // Trend Analysis
  doc.fontSize(12).font("Helvetica-Bold").text("TREND ANALYSIS");
  doc.fontSize(11).font("Helvetica");

  gpaHistory.forEach((h: any, i: number) => {
    const gpa = typeof h.gpa === "number" ? h.gpa : parseFloat(h.gpa as any);
    if (i > 0) {
      const prevGPA =
        typeof gpaHistory[i - 1].gpa === "number"
          ? gpaHistory[i - 1].gpa
          : parseFloat(gpaHistory[i - 1].gpa as any);
      const change = (gpa as number) - (prevGPA as number);
      const trend =
        change > 0 ? "Improved" : change < 0 ? "Declined" : "Stable";
      doc.text(`${h.semester}: ${(gpa as number).toFixed(3)} (${trend})`);
    } else {
      doc.text(`${h.semester}: ${(gpa as number).toFixed(3)} (Starting)`);
    }
  });

  doc.moveDown(1);

  // Recommendations
  doc.fontSize(12).font("Helvetica-Bold").text("RECOMMENDATIONS");
  doc.fontSize(11).font("Helvetica");

  if ((avgGPA as number) >= 3.5) {
    doc.text("• Excellent performance! Continue maintaining high standards.");
  } else if ((avgGPA as number) >= 3.0) {
    doc.text("• Good performance. Focus on consistency in challenging courses.");
  } else if ((avgGPA as number) >= 2.5) {
    doc.text("• Adequate performance. Seek additional support in weak areas.");
  } else {
    doc.text("• Consider academic support services and tutoring.");
  }

  doc.end();

  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    doc.on("finish", () => {
      resolve(Buffer.concat(chunks));
    });
    doc.on("error", reject);
  });

  const fileName = `performance-report-${userId}-${Date.now()}.pdf`;
  const { url } = await storagePut(
    `reports/${fileName}`,
    pdfBuffer,
    "application/pdf"
  );

  return url;
}
